//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseOutput
    {
        public System.DateTime DateStamp { get; set; }
        public double prediction { get; set; }
        public double evaluation { get; set; }
    }
}
